name: CI/CD - Format Check & Deploy

on:
  push:
    branches:
      - main # or 'master' if you're using that

jobs:
  format-check:
    name: Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier Check
        run: npx prettier . --check

  deploy:
    name: Deploy to GitHub Pages
    needs: format-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload site
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.' # root dir (adjust if needed)

      - name: Deploy site
        uses: actions/deploy-pages@v2
